### ISSUE TITLE
Update the robot description and add lidar and imu frames.

### ISSUE THREAD

**Issue by kevinlisun** [FAIRSpace-AdMaLL/jaguar_robot#3]
shall we move the static tf transforms from lio-sam to the jaguar robot?

**Comment by Marwan99** [comment]
I have moved them  here a while back. URDF is [here](https://github.com/FAIRSpace-AdMaLL/jaguar_robot/blob/master/urdf/jaguar.urdf) and launching is happening here:

https://github.com/FAIRSpace-AdMaLL/jaguar_robot/blob/52699c0ab14e9bd391248e1b423270cac8fabbaf/launch/run_simple.launch#L9-L11

Is that ok?

**Comment by Marwan99** [comment]
@kevinlisun Should this be closed now?

**Comment by kevinlisun** [comment]
Yes, well done. @aaxbas You can add this line to ndt_mcl launch, and set a tag whether the real robot is used or not.
